import { useState } from 'react'
import styles from './AdminStudioView.module.css'

const MODE_IMAGES = {
  murder_case: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&h=600&q=80',
  escape_case: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=600&h=600&q=80',
  living_story: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=600&h=600&q=80',
}

export default function AdminStudioView() {
  const [mode, setMode] = useState('murder_case')
  const [theme, setTheme] = useState('')
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [coverImage, setCoverImage] = useState('')
  const [preface, setPreface] = useState('')
  
  const [loading, setLoading] = useState(false)
  const [draft, setDraft] = useState(null)

  const [showToast, setShowToast] = useState(false)

  const handleGenerate = async () => {
    setLoading(true)
    try {
      const res = await fetch('/api/admin/cases/generate-draft', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mode, theme })
      })
      if (!res.ok) throw new Error('Generation failed')
      const data = await res.json()
      
      const generatedTitle = data.game_state.title || (theme ? `${theme}` : 'Untitled Case')
      const generatedHook = data.game_state.episode_hook || data.game_state.preface || 'An intricate mystery generated by AI intelligence.'
      const selectedImg = data.game_state.cover_image || MODE_IMAGES[mode] || MODE_IMAGES.murder_case

      setDraft({
        ...data.game_state,
        cover_image: selectedImg,
        preface: generatedHook
      })
      setTitle(generatedTitle)
      setDescription(generatedHook)
      setCoverImage(selectedImg)
      setPreface(generatedHook)
    } catch (err) {
      console.error(err)
      alert("Failed to generate case")
    } finally {
      setLoading(false)
    }
  }

  const handlePublish = async () => {
    if (!draft || !title || !description) {
      alert("Please fill in title and description")
      return
    }
    
    setLoading(true)
    try {
      const updatedGameState = {
        ...draft,
        title,
        episode_hook: preface || description,
        cover_image: coverImage,
        preface: preface || description
      }

      const res = await fetch('/api/admin/cases/publish-case', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          description,
          mode,
          theme,
          game_state: updatedGameState
        })
      })
      if (!res.ok) throw new Error('Publish failed')
      
      setShowToast(true)
      setTimeout(() => setShowToast(false), 5000)

      setDraft(null)
      setTitle('')
      setDescription('')
      setTheme('')
      setCoverImage('')
      setPreface('')
    } catch (err) {
      console.error(err)
      alert("Failed to publish case")
    } finally {
      setLoading(false)
    }
  }

  const getClueTagClass = (importance) => {
    if (importance === 'critical') return styles.tagCritical
    if (importance === 'red_herring') return styles.tagRedHerring
    return styles.tagSupporting
  }

  return (
    <div className={styles.wrap}>
      <div className={styles.header}>
        <h1>Case Forge</h1>
        <p>AI-driven case generation and curation.</p>
      </div>

      <div className={styles.formCard}>
        <div className={styles.formRow}>
          <div className={styles.inputGroup}>
            <label>Game Mode</label>
            <select value={mode} onChange={e => setMode(e.target.value)} disabled={loading || draft}>
              <option value="murder_case">Murder Case</option>
              <option value="escape_case">Escape Case</option>
              <option value="living_story">Living Story / SoulCast</option>
            </select>
          </div>
          
          <div className={styles.inputGroup}>
            <label>Theme Prompt (Optional)</label>
            <input 
              type="text" 
              placeholder="e.g. A murder on a foggy highway near Pune" 
              value={theme}
              onChange={e => setTheme(e.target.value)}
              disabled={loading || draft}
            />
          </div>
        </div>

        {!draft && (
          <button className={styles.btn} onClick={handleGenerate} disabled={loading}>
            {loading ? "Forging Case & Generating AI Story (takes ~15s)..." : "Generate AI Draft"}
          </button>
        )}
      </div>

      {draft && (
        <div className={styles.reviewPanel}>
          <h2>Draft Review</h2>
          <p style={{ color: 'var(--text-secondary)', marginTop: '-16px' }}>
            Review the AI generated story preface, artwork, suspects, and clues below. Click approve to publish immediately to the Games catalog.
          </p>

          {/* AI Cover & Preface Section */}
          <div style={{ display: 'grid', gridTemplateColumns: '200px 1fr', gap: '20px', background: 'rgba(255,255,255,0.03)', padding: '16px', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.1)', marginBottom: '20px' }}>
            <div>
              <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '8px' }}>🎨 AI Generated Cover</label>
              <img src={coverImage} alt="Cover Art" style={{ width: '100%', height: '160px', objectFit: 'cover', borderRadius: '10px', border: '1px solid rgba(255,255,255,0.15)' }} />
            </div>
            <div>
              <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '8px' }}>📜 AI Story Preface / Hook</label>
              <div style={{ background: '#0e0b16', padding: '12px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.08)', fontSize: '0.95rem', lineHeight: '1.5', color: '#e2e8f0', minHeight: '120px' }}>
                "{preface}"
              </div>
            </div>
          </div>
          
          <div className={styles.inputGroup}>
            <label>Public Title</label>
            <input 
              type="text" 
              value={title} 
              onChange={e => setTitle(e.target.value)} 
              disabled={loading}
            />
          </div>

          <div className={styles.inputGroup}>
            <label>Public Description (Teaser for User Dashboard)</label>
            <textarea 
              placeholder="Write a brief teaser for the players..."
              value={description}
              onChange={e => setDescription(e.target.value)}
              disabled={loading}
            />
          </div>

          <div className={styles.reviewSection}>
            <h3>Suspects</h3>
            <div className={styles.grid}>
              {draft.suspects && draft.suspects.map(s => (
                <div key={s.id} className={styles.card}>
                  <div className={styles.cardHeader}>
                    <span className={styles.cardTitle}>{s.name}</span>
                    <span className={`${styles.tag} ${styles.tagRole}`}>{s.relationship}</span>
                  </div>
                  <div className={styles.cardBody}>{s.public_bio}</div>
                </div>
              ))}
              {(!draft.suspects || draft.suspects.length === 0) && (
                <div className={styles.cardBody}>No suspects generated for this mode.</div>
              )}
            </div>
          </div>

          <div className={styles.reviewSection}>
            <h3>Clues</h3>
            <div className={styles.grid}>
              {draft.clues && draft.clues.map(c => (
                <div key={c.id} className={styles.card}>
                  <div className={styles.cardHeader}>
                    <span className={styles.cardTitle}>{c.title}</span>
                    <span className={`${styles.tag} ${getClueTagClass(c.importance)}`}>{c.importance}</span>
                  </div>
                  <div className={styles.cardBody}>{c.body}</div>
                </div>
              ))}
              {(!draft.clues || draft.clues.length === 0) && (
                <div className={styles.cardBody}>No clues generated for this mode.</div>
              )}
            </div>
          </div>

          <div style={{ display: 'flex', gap: '16px', marginTop: '24px' }}>
            <button className={`${styles.btn} ${styles.btnPublish}`} style={{ flex: 1 }} onClick={handlePublish} disabled={loading}>
              {loading ? "Publishing..." : "Approve & Add to Games"}
            </button>
            <button className={`${styles.btn} ${styles.btnDiscard}`} style={{ flex: 1 }} onClick={() => setDraft(null)} disabled={loading}>
              Discard Draft
            </button>
          </div>
        </div>
      )}

      {showToast && (
        <div className={styles.toast}>
          <span style={{ fontSize: '1.2rem' }}>🎉</span>
          <div>
            <div style={{ fontSize: '1rem', marginBottom: '2px' }}>Case Published!</div>
            <div style={{ fontSize: '0.8rem', fontWeight: '500', opacity: 0.9 }}>It is now playable in Verdicts.</div>
          </div>
        </div>
      )}
    </div>
  )
}
