import AudioStoryPlayer from './AudioStoryPlayer'

export default function DynamicAdminGame({ publishedCase, onBack }) {
  if (!publishedCase) return null

  const gameState = publishedCase.game_state || {}
  const title = publishedCase.title || gameState.title || 'Custom Admin Case'
  const hook = publishedCase.description || gameState.episode_hook || gameState.preface || 'A custom interactive case generated by AI.'
  const coverImage = gameState.cover_image || 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&h=600&q=80'
  const mode = publishedCase.mode || gameState.mode || 'murder_case'

  const beats = [
    {
      id: 'admin_intro',
      type: 'narration',
      text: hook,
    },
    {
      id: 'admin_loop',
      type: 'chat_interaction',
      interactionType: mode === 'escape_case' ? 'escape' : mode === 'living_story' ? 'story' : 'interrogate',
      storyContext: `${title}: ${hook}`,
      roomContext: `${title}: ${hook}`,
      characterName: gameState.suspects && gameState.suspects.length > 0 ? gameState.suspects[0].name : 'Primary Suspect',
      characterContext: gameState.suspects && gameState.suspects.length > 0 ? gameState.suspects[0].public_bio : hook,
      prompt: 'What is your move?',
      maxTurns: 5,
    }
  ]

  return (
    <AudioStoryPlayer
      beats={beats}
      title={title}
      series="Custom Admin Case"
      episode="Special Release"
      accent="#ED4255"
      artworkImage={coverImage}
      isOpenEnded={true}
      onBack={onBack}
    />
  )
}
